# =================================
# Main settings for the TWY8 system.
#
# author: Wu Qianyang, Tao Shengqi, Yang Xingyu
# affiliation: University of Electronic Science and Technology of China
# =================================
workflow:
  dataset_creation: No
  dnn_training: No
  dnn_evaluation: Yes
# ---------------------------------
dataset_creation_settings: !include dataset_creation.yaml
# -----------------------------------
feature_extraction_settings: !include feature_extraction.yaml
# -----------------------------------
dnn_training_settings: !include method_baseline.yaml
# -----------------------------------
dirs_and_files: !include dirs_and_files.yaml
# EOF
